name: ci

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        neovim_tag: [
            # "v0.5.0",
            # "v0.5.1",
            # "v0.6.0",
            # "v0.6.1",
            "stable",
            "v0.7.0",
            "nightly",
          ]
    name: test - nvim ${{ matrix.neovim_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Neovim
        uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim_tag }}

      - name: Neovim Version
        run: nvim --version

      # Installing plugin's dependencies and plenary.nvim
      - name: Prepare Neovim
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/kyazdani42/nvim-web-devicons ~/.local/share/nvim/site/pack/vendor/start/nvim-web-devicons
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start

      - name: Run Tests
        run: make test
