name: lint

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches: [main]

jobs:
  build:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install linter
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: make lint
